### ISSUE TITLE
mother.fucking

### ISSUE THREAD

**Issue by Halima-AddAndCo** [OpenClassrooms-Student-Center/demarrez_votre_projet_avec_python#3]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>page static</title>
</head>
<header><h1>This is a motherfucking website.</h1>

    <h3>And it's fucking perfect.</h3></header>
<body>
    

    <h2><strong>, what the fuck else do you want?</strong></h2>

    <div class="block1">

    <p><strong>You probably build websites and think your shit is special. <br> You think your 13 megabyte parallax-ative home page is going to get you some fucking Awwward banner you can glue to the top corner of your site. You think your 40-pound jQuery file and 83 polyfills give IE7 a boner because it finally has box-shadow. Wrong, motherfucker. Let me describe your perfect-ass website:</strong></p>
        <ul>
            <li>Shit's lightweight and loads fast</li>
            <li>Fits on all your shitty screens</li>
            <li>Looks the same in all your shitty browsers</li>
            <li>The motherfucker's accessible to every asshole that visits your site</li>
            <li>Shit's legible and gets your fucking point across (if you had one instead of just 5mb pics of hipsters drinking coffee)</li>
        </ul>
<h3><strong> guess what, motherfucker:</strong></h3>
<p>You. Are. Over-designing. Look at this shit. It's a motherfucking website. Why the fuck do you need to animate a fucking trendy-ass banner flag when I hover over that useless piece of shit? <br> spent hours on it and added 80 kilobytes to your fucking site, and some motherfucker jabbing at it on their iPad with fat sausage fingers will never see that shit. Not to mention blind people will never see that shit, but they don't see any of your shitty shit.</p><br>

<h3><strong>'s fucking lightweight</strong></h3>
<p>This entire page weighs less than the gradient-meshed facebook logo on your fucking Wordpress site. Did you seriously load 100kb of jQuery UI just so you could animate the fucking background color of a div? You loaded all 7 fontfaces of a shitty webfont just so you could say "Hi." at 100px height at the beginning of your site? You piece of shit.</p>    

<h3><strong>It's responsive</strong></h3>
<p>You dumbass. You thought you needed media queries to be responsive, but no. Responsive means that it responds to whatever motherfucking screensize it's viewed on. This site doesn't care if you're on an iMac or a motherfucking Tamagotchi</p>

<h3><strong>It fucking works</strong></h3>
<p>Look at this shit. You can read it ... that is, if you can read, motherfucker. It makes sense. It has motherfucking hierarchy. It's using HTML5 tags so you and your bitch-ass browser know what the fuck's in this fucking site. That's semantics, motherfucker.</p>
<p>It has content on the fucking screen. Your site has three bylines and link to your dribbble account, but you spread it over 7 full screens and make me click some bobbing button to show me how cool the jQuery ScrollTo plugin is.</p>
<p>Cross-browser compatibility? Load this motherfucker in IE6. I fucking dare you.</p>

<h3><strong>This is a website. Look at it. You've never seen one before.</strong></h3>
<p>Like the man who's never grown out his beard has no idea what his true natural state is, you have no fucking idea what a website is. All you have ever seen are shitty skeuomorphic bastardizations of what should be text communicating a fucking message. This is a real, naked website. Look at it. It's fucking beautiful.</p>

<h3>Yes, this is fucking satire, you fuck</h3>
<p><strong>I'm not actually saying your shitty site should look like this. What I'm saying is that all the problems we have with websites are ones we create ourselves. Websites aren't broken by default, they are functional, high-performing, and accessible. You break them. You son-of-a-bitch.</strong></p>
</div>

    <div class="footer">
        <p>"Good design is as little design as possible."<br>
                - some German motherfucker</p>
    </div>

    <script src="//www.google-analytics.com/analytics.js"></script>
_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
    <div><h3><strong>Epilogue</strong></h3>
    <p>From the philosophies expressed (poorly) above,<a href="index1.html"> txti</a> was created. You should try it today to make your own motherfucking websites.</p>
    </div>
</body>
</html>

**Comment by ghost** [comment]
Sorry but you know... too many m...f...ing and m...f..er kept me off from even going to look at it..

Just like you said for the code, your pitch is too heavy imho.

________________________________
De : Halima <notifications@github.com>
Envoyé : lundi, 23 septembre 2019 20:54
À : OpenClassrooms-Student-Center/demarrez_votre_projet_avec_python <demarrez_votre_projet_avec_python@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [OpenClassrooms-Student-Center/demarrez_votre_projet_avec_python] mother.fucking (#3)

<title>page static</title>
This is a motherfucking website.

<h3>And it's fucking perfect.</h3></header>


<h2><strong>, what the fuck else do you want?</strong></h2>

<div class="block1">

<p><strong>You probably build websites and think your shit is special. <br> You think your 13 megabyte parallax-ative home page is going to get you some fucking Awwward banner you can glue to the top corner of your site. You think your 40-pound jQuery file and 83 polyfills give IE7 a boner because it finally has box-shadow. Wrong, motherfucker. Let me describe your perfect-ass website:</strong></p>
    <ul>
        <li>Shit's lightweight and loads fast</li>
        <li>Fits on all your shitty screens</li>
        <li>Looks the same in all your shitty browsers</li>
        <li>The motherfucker's accessible to every asshole that visits your site</li>
        <li>Shit's legible and gets your fucking point across (if you had one instead of just 5mb pics of hipsters drinking coffee)</li>
    </ul>


guess what, motherfucker:

You. Are. Over-designing. Look at this shit. It's a motherfucking website. Why the fuck do you need to animate a fucking trendy-ass banner flag when I hover over that useless piece of shit?
spent hours on it and added 80 kilobytes to your fucking site, and some motherfucker jabbing at it on their iPad with fat sausage fingers will never see that shit. Not to mention blind people will never see that shit, but they don't see any of your shitty shit.

's fucking lightweight

This entire page weighs less than the gradient-meshed facebook logo on your fucking Wordpress site. Did you seriously load 100kb of jQuery UI just so you could animate the fucking background color of a div? You loaded all 7 fontfaces of a shitty webfont just so you could say "Hi." at 100px height at the beginning of your site? You piece of shit.

It's responsive

You dumbass. You thought you needed media queries to be responsive, but no. Responsive means that it responds to whatever motherfucking screensize it's viewed on. This site doesn't care if you're on an iMac or a motherfucking Tamagotchi

It fucking works

Look at this shit. You can read it ... that is, if you can read, motherfucker. It makes sense. It has motherfucking hierarchy. It's using HTML5 tags so you and your bitch-ass browser know what the fuck's in this fucking site. That's semantics, motherfucker.

It has content on the fucking screen. Your site has three bylines and link to your dribbble account, but you spread it over 7 full screens and make me click some bobbing button to show me how cool the jQuery ScrollTo plugin is.

Cross-browser compatibility? Load this motherfucker in IE6. I fucking dare you.

This is a website. Look at it. You've never seen one before.

Like the man who's never grown out his beard has no idea what his true natural state is, you have no fucking idea what a website is. All you have ever seen are shitty skeuomorphic bastardizations of what should be text communicating a fucking message. This is a real, naked website. Look at it. It's fucking beautiful.

Yes, this is fucking satire, you fuck

I'm not actually saying your shitty site should look like this. What I'm saying is that all the problems we have with websites are ones we create ourselves. Websites aren't broken by default, they are functional, high-performing, and accessible. You break them. You son-of-a-bitch.

"Good design is as little design as possible."
- some German motherfucker

<script src="//www.google-analytics.com/analytics.js"></script>


________________________________

<div><h3><strong>Epilogue</strong></h3>
<p>From the philosophies expressed (poorly) above,<a href="index1.html"> txti</a> was created. You should try it today to make your own motherfucking websites.</p>
</div>

**Comment by Halima-AddAndCo** [comment]
Je suis d'accord
Bonne la base c'est un travail scolaire a envoyer d'un site déjà existant .


Le lun. 23 sept. 2019 à 21:16, Régis Behmo <notifications@github.com> a
écrit :
